### ISSUE TITLE
Broken generated image from decoded data

### ISSUE THREAD

**Issue by AliBayatMokhtari** [image-js/tiff#45] opened 2023-05-28 10:04 UTC
I have decoded this file: [Link](https://filesamples.com/samples/image/tiff/sample_640%C3%97426.tiff) and the output is [Preview](https://fastupload.io/NRbkSEgKjao2yG1/preview) or [Download](https://fastupload.io/NRbkSEgKjao2yG1/file)

the source code for getting image/png file is:
```typescript
/** buffer is of type ArrayBuffer which is read from sample file */
const tiffIfds = decode(buffer);

const first = tiffIfds[0];

const canvas = document.createElement("canvas");
canvas.width = first.width;
canvas.height = first.height;

const ctx = canvas.getContext("2d", { alpha: first.alpha });

const imageData = ctx?.createImageData(canvas.width, canvas.height);
imageData?.data.set(first.data);

ctx?.putImageData(imageData!, 0, 0);

const pngImage = canvas.toDataURL("image/png");

const imgEl = document.getElementById("my-image") as HTMLImageElement;

if (imgEl) imgEl.src = pngImage;
```
and the HTML markup is simple as:
```html
<div>
    <img id="my-image" />
</div>
```

**Comment by targos** [comment] 2023-05-29 07:50
The problem is that you cannot just set the image data like that, because this tiff file has only three channels (RGB, no alpha). ImageData objects always contain RGBA data.

**Comment by AliBayatMokhtari** [comment] 2023-05-29 11:29
> The problem is that you cannot just set the image data like that, because this tiff file has only three channels (RGB, no alpha). ImageData objects always contain RGBA data.

So how can i convert such image to image/png base64?
Any clue would be helpful. Thank uou

**Comment by targos** [comment] 2023-05-31 08:46
You can use [`image-js`](https://github.com/image-js/image-js):

```js
import { Image } from 'image-js';
const img = await Image.load(data);
const url = img.toDataURL()
```

Feel free to ask more questions, but I'm closing this issue because the data returned by the decoder is correct.

**Closed by targos** 2023-05-31 08:46 UTC
